# A basic config file for the snoRNA feature analysis pipeline.

#=====================================================
# GLOBAL SETTINGS
#=====================================================

# This is a flag to determine whether to generate plots.
# The `all` rule will check this setting.
generate_plots: true

# This is a flag to determine whether to export tables.
# The `all` rule will check this setting.
export_tables: true


#=====================================================
# THREADS AND CORES
#=====================================================

# Define the number of cores/threads for rules that can be parallelized.
# Use this in your Snakefile like `threads: config["cores"]["setup_rule"]`
cores: 1
threads: 1
#=====================================================
# INPUT FILES
#=====================================================

# Define the paths to your raw input data files.
# This makes it easy to change file locations without editing the Snakefile itself.
input_files:
  snodb: "data/raw/snoDB_data.xlsx"
  met_sites: "data/raw/snoDB_rRNA_interactions.xlsx"
  sno_boxes: "data/raw/cd_boxes.tsv"

#=====================================================
# OUTPUT FILES
#=====================================================

output_files:
  guide:
  info_box:
  possible_boxes:
  scores:
  snorna_machine_learning:
  #plots
  all_distance:
  all_logos:
  down_motif_score_distribution:
  up_motif_score_distribution:
  motif_score_snoDB_distribution:
  guide_width:
  #tables
  pfm_cbox_snoDb: 
  pfm_dbox_snoDb:
  pfm_cbox_prime_snoDb:
  pfm_dbox_prime_snoDb:
  # ...

#=====================================================
# MACHINE LEARNING 
#=====================================================
  
machine_learning:
  model:
  test_size:
  
  
#   # snoMatcher NEW Configuration File
# # 
# # Input files
# input_files:
#   snodb: "data/raw/snoDB_data.xlsx"
#   met_sites: "data/raw/snoDB_rRNA_interactions.xlsx"
#   sno_boxes: "data/raw/cd_boxes.tsv"
#   # other: "data/raw/[file]"
# # 
# # Processing options
# generate_plots: true
# export_tables: true
# # 
# # Computational resources
# threads: 4
# memory: 8000  # Memory in MB
# # 
# # Analysis parameters
# scoring:
#   min_guide_length: 7
#   max_guide_length: 18
#   mismatch_threshold: 2
# # 
# # Output options
# plots:
#   format: "pdf"
#   width: 10
#   height: 8
#   dpi: 300
# # 
# tables:
#   format: "csv"
# #   
# # # ML parameters (for future expansion)
# machine_learning:
#   model_type: "random_forest"
#   cv_folds: 5
#   test_size: 0.2
